### ISSUE TITLE
Properly indicate dependencies UI Lib as both sided or make it optional

### ISSUE THREAD

**Issue by ghost** [DAQEM/Arc#26]
This mod relies on UI LIb, however UI Lib is an exclusively client sided mod. Despite that, this mod requires it while still being loaded on the server.

**Comment by DAQEM** [comment]
Correct. On Forge, UI Lib is treated as a client side only dependency, but on Fabric, this feature hasn't been implemented yet. And I'd rather have people install UI Lib on the server side for Fabric than making it optional, just for Fabric. 

I did some research and found that [this feature almost got implemented](https://github.com/FabricMC/fabric-loader/pull/370) back in 2021, but for some reason they decided not to...
