### ISSUE TITLE
Incompatibility with EasyNPC (1.20.1 Forge)

### ISSUE THREAD

**Issue by yellowcake3d** [DAQEM/Arc#34]
Description of the crash
If EasyNPC and arc lib are installed, when you spawn an npc, the game crashes

Steps to reproduce the crash

1.Install easynpc

2.Install ArcLib with dependencies (Arclib, Architecturyapi, UI Lib, SuperMartijn core lib and SuperMartijn config lib)

3.Launch the game, create a new world and use an npc spawn egg to spawn an npc

Logs
debug log - https://pastebin.com/yTZtG5v4
crash.log - https://pastebin.com/xtCvhDgC

Additional context:
Originally reported this incompatibility to EasyNPC github, and the mod author provided some [additional information](https://github.com/MarkusBordihn/BOs-Easy-NPC/issues/280#issuecomment-2275476372) to why this crash might happen and asked to report this issue to you as well

**Comment by DAQEM** [comment]
Fix has been uploaded to CurseForge and Modrinth under version 1.7-1.20.1. Thank you for reporting.
