### ISSUE TITLE
Question on mod capabilites

### ISSUE THREAD

**Issue by ghost** [DAQEM/Arc#37]
hi, I have some questions about what this mod can do I want to use this item-restrictions and pufferfish's skills to create a skill tree to unlock the use of stuff, is this possible? the wiki looks very incomplete so I'm asking here

**Comment by DAQEM** [comment]
For this to actually work, you'll need to create a mod that adds Arc Lib compatibility to Pufferfish's Skills. I'm not very familiar with Pufferfish's Skills myself.
